=== azapps/XML-feature-list/xml/featurelist.dtd
<!--
	 FEATURELIST DTD

	 Author: Anatoly Zelenin <az@azapps.de>
	 Date: 2013-05-30
-->
<!ELEMENT featurelist (author,title,header_title,participants,client,description,features)>
<!ELEMENT author (EMPTY)>
<!ATTLIST author
	name CDATA #REQUIRED
	email CDATA #REQUIRED >

<!ELEMENT title (#PCDATA)>
<!ELEMENT client (#PCDATA)>
<!ELEMENT header_title (#PCDATA)>

<!ELEMENT participants (participant+)>
<!ELEMENT participant (#PCDATA)>
<!ATTLIST participant
	function CDATA #IMPLIED >

<!ELEMENT features (feature+)>
<!ELEMENT feature (description?,functions?,data?,tests?,features?)>
<!ATTLIST feature
	name CDATA #REQUIRED
	short CDATA #REQUIRED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT functions (function+)>
<!ELEMENT function (#PCDATA)>
<!ELEMENT data (description,item+)>

<!ELEMENT tests (description,test+)>
<!ELEMENT test (#PCDATA)>

<!ELEMENT b (#PCDATA)>
<!ELEMENT br EMPTY>
<!ELEMENT list (item+)>
<!ELEMENT link (#PCDATA)>
<!ATTLIST link
	to CDATA #REQUIRED>

<!ELEMENT item (#PCDATA)>
<!ATTLIST item
	foreign CDATA #IMPLIED
	name CDATA #IMPLIED>

<!ELEMENT img EMPTY>
<!ATTLIST img
	src CDATA #REQUIRED>

=== azapps/XML-feature-list/example.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE featurelist SYSTEM "xml/featurelist.dtd">
<featurelist>
	<author name="Anatoly Zelenin" email="az@azapps.de" />
	<features>
		<feature name="Testfeaturelist" short="TF">
			<description>It's just a test</description>
			<functions>
				<function>Functionslist</function>
				<function>Some data</function>
				<function>Tests</function>
				<function>And some subfeatures</function>
			</functions>
			<data>
				<item>Test</item>
				<item>Foo</item>
			</data>
			<tests>
				<test>Test for valid XML</test>
				<test>is the \LaTeX correct?</test>
			</tests>
		</feature>
	</features>
</featurelist>
